// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfIUHnwNv6RuZDWBNY_nRo3jqBPa5Vn3w',
    appId: '1:659360301138:android:e4bbaf15deb170775a1f8b',
    messagingSenderId: '659360301138',
    projectId: 'storeecomapp',
    storageBucket: 'storeecomapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOK8d6Tx-qedCpj5mOXfi7T2od7JYB1_w',
    appId: '1:659360301138:ios:87e9122fe7d0c4795a1f8b',
    messagingSenderId: '659360301138',
    projectId: 'storeecomapp',
    storageBucket: 'storeecomapp.appspot.com',
    androidClientId: '659360301138-5i22k14sm993ou13go0ltpt6kbm3kjd8.apps.googleusercontent.com',
    iosClientId: '659360301138-174bd606oubl1ivgvq50hkmbo0mbj39g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterpro',
  );

}